version: "3.1"

services:
  project_database:
    restart: always
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: project_database
      MYSQL_ROOT_USER: admin
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret


